AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: List all idols.
Resources:
  FindAllIdols:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          TABLE_NAME: 
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /idols
            Method: get