version: 0.2
env:
  variables:
    S3_BUCKET: "hello-serverless-morichan"
    PACKAGE: "https://github.com/pisa-kun/Practive-Hands-On-Serverless-Applications-with-Go"
    BINNAME: "CICDMethod"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      #- go get -u github.com/golang/lint/golint

  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - go get -t ./...
      #- golint -set_exit_status
      - go vet .
      - go test .

  build:
    commands:
      - GOOS=linux go build -o $BINNAME main.go
      - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip $BINNAME
      - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_BUCKET/

  post_build:
    commands:
      - aws lambda update-function-code --function-name $BINNAME --s3-bucket $S3_BUCKET --s3-key $CODEBUILD_RESOLVED_SOURCE_VERSION.zip